Game controller
Dustfoxx/board-game-madness pull request #6
Opened 2024-11-22 16:48 UTC by Dustfoxx

* Added GameController logic
* New turns and tracking turn order and number
* Currently does not track timeline of events which i believe would fit in here
* Checkmove also in this pr but untested. Temple tiles are missing.
  * Test will be implemented through another branch

2024-11-25 09:15 UTC, mrPaintMan approved these changes
Lookes awesome! I liked how u used the mocking library to really focus on the important parts in the testing!!

2024-11-25 09:15 UTC, mrPaintMan commented on Project/core/src/main/java/Controller/GameController.java
> +    private Model.Player players[] = new Player[6];
Could this be renamed to something more descriptive?  Im having a hard time following the difference between players and gamePlayers and game
state.getPlayers() used through out here!

2024-11-25 09:15 UTC, mrPaintMan commented on Project/core/src/main/java/Controller/GameController.java
> +    List<RougeAgent> agents = new ArrayList<RougeAgent>();
It seems like this list is only used in the constrructor, could it be used as a stack variable instead of a class field?

2024-11-29 13:55 UTC, Vilmavds requested changes

2024-11-29 13:55 UTC, Vilmavds commented on Project/core/src/main/java/Controller/CheckMove.java
This file is not used, and should maybe not be present in this PR. Maybe we can delete it from this PR and have it in a later PR?

2024-11-29 13:55 UTC, Vilmavds commented on Project/core/src/main/java/Controller/GameController.java
> +        }
This playerTurnOrder array only works for some cases, but not for all. For example, if we have 1 recruiter and 3 agents, the array won't let the agens play equally often. I suggest we let it be and mark it as an issue which we correct sometime in the future.

2024-11-29 13:55 UTC, Vilmavds commented on Project/core/src/main/java/Controller/GameController.java
> +    private Game gameState;
Should the GameController contain and store the gameState? Or should it be somewhere outside in main?

2024-11-29 13:57 UTC, Vilmavds commented on Project/core/src/main/java/Controller/GameController.java
> +            if (gameState.getCurrentTime() >= 8) {// IDK how many turns were max
Maybe put this 8 as an attribute of the class to avoid magic numbers?

2024-11-29 14:11 UTC, merged